from typing import TYPE_CHECKING, Union

import spacy.tokens as spacy
import stanza.models.common.doc as stanza

if TYPE_CHECKING:
    from brontology.language_processing.coreference_resolution import CorefAnnotation, CorefChain


class Token(spacy.Token):
    class CustomAttrs:
        stanza_tokens: list[tuple[tuple[int, int], stanza.Token]] | None
        """The tokens generated by stanza matching to this spacy token.
        This can be multiple or none at all, depending on tokenization differences.
        
        Tuple:
            1. The token's index [sentence index, token index].
            2. The token itself."""
        coref: Union["CorefAnnotation", None]

    _: CustomAttrs


class Doc(spacy.Doc):
    class CustomAttrs:
        stanza_doc: stanza.Document | None
        coref_chains: list["CorefChain"]

    _: CustomAttrs

spacy.Token.set_extension("stanza_tokens", default=None)
spacy.Token.set_extension("coref", default=None)
spacy.Doc.set_extension("stanza_doc", default=None)
spacy.Doc.set_extension("coref_chains", default=None)


DocSpan = Doc | spacy.Span
"""Union of `Doc` and `Span`"""
