from dataclasses import dataclass
from itertools import chain
from typing import Generator, Iterator, Iterable

import spacy.tokens as spacy
import stanza as stanza_core
import stanza.models.common.doc as stanza
from spacy.tokens import Span

from brontology.config import Model


@dataclass
class CorefChain:
    """A coref chain consisting of its representative and non-representative members."""

    doc: "Doc"
    representative_: tuple[int, int]
    non_representatives_: list[tuple[int, int]]

    def __post_init__(self):
        # Register this coref chain to all contained tokens.
        for token in self.representative:
            token: Token
            token._.coref = CorefAnnotation(True, self)

        for span in self.non_representatives:
            for token in span:
                token: Token
                token._.coref = CorefAnnotation(False, self)

        self.doc._.coref_chains.append(self)

    @property
    def representative(self) -> Span:
        """The representative span for the coref chain."""
        return self.doc[slice(*self.representative_)]

    @property
    def non_representatives(self) -> Generator[Span, None, None]:
        """The non-representative spans of the coref chain."""
        return (self.doc[slice(*r)] for r in self.non_representatives_)

    @property
    def members(self) -> Generator[Span, None, None]:
        """All members (representative and non-representative) of the coref chain."""
        return (m for m in chain([self.representative], self.non_representatives))


@dataclass
class CorefAnnotation:
    """An annotation linking a token to a `CorefChain`.
    This includes the information whether this token is part of the representative span for the entire chain.
    """

    is_representative: bool
    chain: CorefChain


class Token(spacy.Token):
    class CustomAttrs:
        stanza_tokens: list[tuple[tuple[int, int], stanza.Token]] | None
        """The tokens generated by stanza matching to this spacy token.
        This can be multiple or none at all, depending on tokenization differences.
        
        Tuple:
            1. The token's index [sentence index, token index].
            2. The token itself."""
        coref: CorefAnnotation | None

    _: CustomAttrs


class Doc(spacy.Doc):
    class CustomAttrs:
        stanza_doc: stanza.Document | None
        coref_chains: list[CorefChain]

    _: CustomAttrs


spacy.Token.set_extension("stanza_tokens", default=None)
spacy.Token.set_extension("coref", default=None)
spacy.Doc.set_extension("stanza_doc", default=None)
spacy.Doc.set_extension("coref_chains", default=None)


def is_in_char_range(spacy_token: Token, stanza_token: stanza.Token) -> bool:
    """Checks if the `stanza_token` is within the character span of the `spacy_token`.
    If the `spacy_token` is the last token of the doc, this will always be true."""
    try:
        return stanza_token.start_char < spacy_token.nbor().idx
    except IndexError:
        return True


def merge_stanza_to_spacy(stanza_doc: stanza.Document, spacy_doc: Doc) -> None:
    """Merges a stanza `Document` into a spacy `Doc`
    by linking all attributes of the stanza `Document` to custom attributes in the spacy `Doc`.
    This includes document-level information as well as token-level information.

    The spacy `Doc` is modified in-place.

    :raises ValueError:
        When trying to match documents with different source texts.
    """
    if stanza_doc.text != spacy_doc.text:
        raise ValueError("Cannot merge documents with different source texts.")

    spacy_doc._.stanza_doc = stanza_doc
    for token in spacy_doc:
        token: Token
        token._.stanza_tokens = list()

    stanza_tokens_generator: Iterator[tuple[tuple[int, int], stanza.Token]] = (
        ((sent_index, token_index), token)
        for sent_index, sent in enumerate(stanza_doc.sentences)
        for token_index, token in enumerate(sent.tokens)
    )
    stanza_index, stanza_token = next(stanza_tokens_generator)
    try:
        for spacy_token in spacy_doc:
            spacy_token: Token
            while is_in_char_range(spacy_token, stanza_token):
                spacy_token._.stanza_tokens.append((stanza_index, stanza_token))
                stanza_index, stanza_token = next(stanza_tokens_generator)
    except StopIteration:
        ...

    merge_corefs(stanza_doc, spacy_doc)


def merge_corefs(stanza_doc: stanza.Document, spacy_doc: Doc):
    # Set up the custom attribute.
    spacy_doc._.coref_chains = list()

    for coref_chain in stanza_doc.coref:
        coref_chain: stanza.CorefChain

        representative: tuple[int, int] | None = None
        non_representatives: list[tuple[int, int]] = list()

        # Find the spacy tokens that match the range defined in the coref mentions.
        for mention_index, mention in enumerate(coref_chain.mentions):
            mention: stanza.CorefMention

            is_representative = mention_index == coref_chain.representative_index
            index_range = (mention.start_word, mention.end_word)

            collected_tokens = _match_tokens_in_stanza_range(
                list(spacy_doc), mention.sentence, index_range
            )

            span = (collected_tokens[0].i, collected_tokens[-1].i + 1)
            if is_representative:
                representative = span
            else:
                non_representatives.append(span)

        if representative is None:
            raise ValueError(
                "Cannot create a `CorefChain` without a representative value."
            )
        # Create the coref chain. It registers itself on the doc and token automatically.
        CorefChain(
            spacy_doc,
            representative_=representative,
            non_representatives_=non_representatives,
        )


def _match_tokens_in_stanza_range(
    tokens: Iterable[spacy.Token], stanza_sentence: int, stanza_range: tuple[int, int]
):
    """Finds all tokens from the `tokens`
    which have a `.stanza_token` of which the index is within the `stanza_range`."""
    collected_tokens = list()
    for spacy_token in tokens:
        spacy_token: Token
        for stanza_index, _ in spacy_token._.stanza_tokens:
            if stanza_index[0] != stanza_sentence:
                continue
            if stanza_range[0] <= stanza_index[1] < stanza_range[1]:
                collected_tokens.append(spacy_token)
                break  # Each token must only be added once.
    return collected_tokens


if __name__ == "__main__":
    _sents = [
        "The cats were startled by the dog as it growled at them.",
        "John Bauer works at Stanford.  He has been there 4 years. Also he likes to sit at the coffe machine, which breaks quite often.",
        "Killer Whales tend to hunt other dolphins. These dolphins often also get hunted by sharks.",
    ]

    _all_sents = " ".join(_sents)

    _stanza_nlp = stanza_core.Pipeline("en", processors="tokenize,coref")
    _stanza_doc: stanza.Document = _stanza_nlp(_all_sents)

    _spacy_doc: Doc = Model.inst(_all_sents)

    print("Matched Tokens:")
    merge_stanza_to_spacy(_stanza_doc, _spacy_doc)
    for _token in _spacy_doc:
        print()
        print([_token.text])
        print([t[1].text for t in _token._.stanza_tokens])

    print()
    print("Corefs:")
    for _coref in _spacy_doc._.coref_chains:
        print()
        print("Representative:")
        print(_coref.representative)
        print("Non-Representative:")
        print(*_coref.non_representatives, sep="\n")
